 const API_BASE_URL = import.meta.env.VITE_BASE_API_URL;
 export const RESET_PASSWORD = `${API_BASE_URL}/reset`;
 export const TOKEN_URL = `${API_BASE_URL}/login`;
 export const SIGN_UP_URL = `${API_BASE_URL}/register`;
 export const REFRESH_URL = `${API_BASE_URL}/refresh`;
 export const RESET_PASSWORD_CONFIRM = `${API_BASE_URL}/reset-confirm`;
 export const VEHICAL_DATA_URL = `${API_BASE_URL}/vehicles`;
 export const USER_PROFILE_URL = `${API_BASE_URL}/profile`;
 export const UPLOAD_IMAGE_URL = `${API_BASE_URL}/profile/upload-image`;